# Generated by Django 4.0.1 on 2022-02-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='impo',
            field=models.BooleanField(default=False),
        ),
    ]
